---
- name: Install OS Packages
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - libselinux-python

- include: RedHat-rpm.yml
  when: zookeeper_install_tarball == False

- include: tarball.yml
  when: zookeeper_install_tarball

- include: upstart.yml
  when: zookeeper_install_tarball
  tags: deploy

- include: systemd.yml
  when: zookeeper_install_tarball
  tags: deploy
