---
- name: Install selinux python3 bindings
  pip: name=selinux state=latest executable=pip3

- include: RedHat-rpm.yml
  when: zookeeper_install_tarball == False

- include: tarball.yml
  when: zookeeper_install_tarball

- include: upstart.yml
  when: zookeeper_install_tarball
  tags: deploy

- include: systemd.yml
  when: zookeeper_install_tarball
  tags: deploy
